### ISSUE TITLE
Objective C implementation

### ISSUE THREAD

**Issue by Heidi0039** [3qnexx/nexxPLAY-iOS#13]
I have successfully implemented NexxPLAY using Swift, with all desired functionality however in my ObjC approach I am unable to fully implement certain functionality.

After Instanciating my NexxPLAYView, NexxPLAYEnvironment and NexxPLAYConfiguration as intended, i can View Videos already.

Things like NexxPLAYEnvironment.alwaysInFullscreen however, are unavailable.
I am using **[self.env alwaysInFullscreen: YES];**.

When trying to implement  **[self.player autoresizesSubviews: YES]** I noticed, that for ObjC (unlike Swift) I need to use a specific setter function like so: **[self.player setAutoresizesSubviews: YES]**.

I would expect similar functionality for setting alwaysInFullscreen, but I was unable to find said function.
This is also the case for many other variables I would like to set.

**Comment by DanielLeberle** [comment]
We just released v6.0.5 with a fix for this issue!
Please add this version to your project and let me know if there are any further problems!

**Comment by Heidi0039** [comment]
I can now use Fullscreen as expected.
I still have no access to any Notification value.
Meaning I cannot access nexxPlay.nexxPlayNotificationFullscreenExited as I have no access to the nexxPlay module in ObjC. This is working as intended using Swift.

I can however use nexxPlayVersionNumber and nexxPlayVersionString, as they are exposed in the nexxPlay.h file.

**Comment by DanielLeberle** [comment]
you can string compare `notification.name` with the names in the documentation.
The only difference between the variable name and the sent notification name is the first letter that is uppercased.
So e.g. nexxPlay.nexxPlayExitFullscreenNotification should have the string @"NexxPlayExitFullscreenNotification".

We will rewrite the interface for the next version in order to make the notification variables also available for Obj-C

**Comment by Heidi0039** [comment]
Thank you. 
I was unaware of how the Notification Strings are built up.

This solved my issue.
